@echo off
rem ============================================================
rem  bundle_core.bat - Pack project core files into one text file.
rem  Format: for each file, output PATH / FILE / CONTENT.
rem  Output:  core_source_bundle.txt (project root)
rem ============================================================
setlocal

powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$root='%~dp0';" ^
  "$out=$root+'core_source_bundle.txt';" ^
  "if (Test-Path $out) { Remove-Item $out -Force };" ^
  "$sb=New-Object System.Text.StringBuilder;" ^
  "[void]$sb.AppendLine('============================================================');" ^
  "[void]$sb.AppendLine('CORE FILES BUNDLE');" ^
  "[void]$sb.AppendLine('Generated by bundle_core.bat');" ^
  "[void]$sb.AppendLine('============================================================');" ^
  "$files=@(Get-ChildItem -LiteralPath ($root+'app\src\main') -Recurse -File);" ^
  "foreach($n in @('build.gradle.kts','settings.gradle.kts','gradle.properties')){ $p=$root+$n; if(Test-Path -LiteralPath $p){ $files += Get-Item -LiteralPath $p } };" ^
  "foreach($f in $files){" ^
  "  [void]$sb.AppendLine('');" ^
  "  [void]$sb.AppendLine('============================================================');" ^
  "  [void]$sb.AppendLine('[PATH] '+$f.FullName);" ^
  "  [void]$sb.AppendLine('[FILE] '+$f.Name);" ^
  "  [void]$sb.AppendLine('============================================================');" ^
  "  [void]$sb.AppendLine([System.IO.File]::ReadAllText($f.FullName,[System.Text.Encoding]::UTF8))" ^
  "};" ^
  "[System.IO.File]::WriteAllText($out,$sb.ToString(),(New-Object System.Text.UTF8Encoding($false)));" ^
  "Write-Host ('Done. Output: '+$out)"

echo.
pause
